<Project Sdk="Aspire.AppHost.Sdk/13.2.4">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>ff34aa23-fac0-459b-805c-9c320d163933</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.SqlServer" Version="13.2.4" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FunEvents.API\FunEvents.API.csproj" />
  </ItemGroup>

</Project>
